### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by drzraf** [paviliondev/discourse-ratings#9]
Any hope the feature could be accessible through the API?
(http://docs.discourse.org/)
That'd would a huge win for integration (eg: mobile users)

 Side note: any hint about how anonymous users are handled?

**Comment by davidmh** [comment]
@drzraf the topic endpoint includes all the properties you would need.

```
GET :base_url/t/:id.json
```

```json
{
    "post_stream": {
        "posts": [{ "rating": 4 }]
    },
    "average_rating": 4,
    "rating_enabled": true,
    "rating_count": 1,
    "can_rate": null,
    "rating_target_id": "",
    "has_ratings": true
}
```
